#@ load("@ytt:data", "data")

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: dependency-track-encryption-key
  namespace: dependency-track
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      encryption-key: $(value)
