#@ load("@ytt:data", "data")
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-dependency-track
  namespace: dependency-track
  annotations:
    kapp.k14s.io/change-group: postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: #@ data.values.postgresql.instances
  storage:
    size: #@ data.values.postgresql.storage.size
